name: Staging - CI & CD

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Staging - Testing
    uses: ./.github/workflows/ci-testing.yml

  build-and-push:
    name: Staging - Artifact Registry GCP
    uses: ./.github/workflows/ci-gcp-artifact-registry.yml
    needs: testing
