name: Staging - CI & CD

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ./.github/workflows/ci-testing.yml

