name: Production - CI & CD

on:
  workflow_dispatch:
  release:
    types: [published]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  testing:
    name: Production - Testing
    uses: ./.github/workflows/ci-testing.yml

  gcp-deployment:
    name: Production - Google Cloud Platform
    uses: ./.github/workflows/gcp-deployment.yml
    with:
      environment: production
    needs: testing
