name: Staging - CI & CD

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  testing:
    name: Staging - Testing
    uses: ./.github/workflows/ci-testing.yml

  gcp-deployment:
    name: Staging - Google Cloud Platform
    uses: ./.github/workflows/gcp-deployment.yml
    with:
      environment: staging
    needs: testing
